import Reydel from '@/assets/profiles/Reydel.jpg';

export const Collaborator = [
  {
    id: 1,
    type: 'large',
    title: 'Jedepota Agayan Drip',
    subtitle: 'Event Coordinator',
    description: 'Organizing seamless corporate and community events with a focus on engagement.',
    email: 'jed@gmail.com',
    image: Reydel,
    gridConfig: {
      colSpan: 4,
      rowSpan: 3,
    },
    backgroundColor: 'bg-blue-100',
    buttonText: 'Collab',
  },
  {
    id: 2,
    type: 'large',
    title: 'Kulturang Pinoy',
    subtitle: 'Cultural Events Team',
    description: 'Showcasing Filipino traditions through events.',
    email: 'info@kulturangpinoy.com',
    image: Reydel,
    gridConfig: {
      colSpan: 2,
      rowSpan: 2,
    },
    backgroundColor: 'bg-green-100',
    buttonText: 'Collab',
  },
  {
    id: 3,
    type: 'small',
    title: 'Maria Santos',
    subtitle: 'Concert Organizer',
    description: 'Bringing OPM artists to the stage.',
    email: 'maria.santos@example.com',
    image: Reydel,
    gridConfig: {
      colSpan: 1,
      rowSpan: 1,
    },
    backgroundColor: 'bg-black',
    buttonText: 'Collab',
  },
  {
    id: 4,
    type: 'small',
    title: 'Team Lakbay',
    subtitle: 'Travel & Advent Club',
    description: 'Curating fun travel experiences.',
    email: 'contact@teamlakbay.ph',
    image: Reydel,
    gridConfig: {
      colSpan: 1,
      rowSpan: 1,
    },
    backgroundColor: 'bg-red-100',
    buttonText: 'Collab',
  },
  {
    id: 5,
    type: 'extra-small',
    title: 'Gabriel Reyes',
    subtitle: 'Festival Director',
    description: 'Managing cultural festivals.',
    email: 'gabriel.reyes@example.com',
    image: Reydel,
    gridConfig: {
      colSpan: 1,
      rowSpan: 4,
    },
    backgroundColor: 'bg-purple-100',
    buttonText: 'Collab',
  },
  {
    id: 6,
    type: 'extra-small',
    title: 'Barkada Esports',
    subtitle: 'Gaming Tournament Hosts',
    description: 'Hosting esports battles.',
    email: 'support@barkadaesports.gg',
    image: Reydel,
    gridConfig: {
      colSpan: 1,
      rowSpan: 4,
    },
    backgroundColor: 'bg-yellow-100',
    buttonText: 'Collab',
  },
  {
    id: 7,
    type: 'large',
    title: 'Luzviminda Productions',
    subtitle: 'Event Management Agency',
    description: 'Bringing grand event concepts to reality with world-class planning and execution.',
    email: 'hello@luzvimindaproductions.ph',
    image: Reydel,
    gridConfig: {
      colSpan: 4,
      rowSpan: 8,
    },
    backgroundColor: 'bg-yellow-100',
    buttonText: 'Collab',
  },
  {
    id: 8,
    type: 'large',
    title: 'Anna Mendoza',
    subtitle: 'Wedding Planner',
    description: 'Creating magical wedding experiences tailored to the couple’s vision and culture.',
    email: 'anna.mendoza@example.com',
    image: Reydel,
    gridConfig: {
      colSpan: 2,
      rowSpan: 20,
    },
    backgroundColor: 'bg-yellow-100',
    buttonText: 'Collab',
  },
  {
    id: 9,
    type: 'large',
    title: 'TechTalk PH',
    subtitle: 'Tech Conference Organizers',
    description: 'Hosting conferences that bring together innovators, developers, and startups.',
    email: 'info@techtalkph.com',
    image: Reydel,
    gridConfig: {
      colSpan: 2,
      rowSpan: 16,
    },
    backgroundColor: 'bg-yellow-100',
    buttonText: 'Collab',
  },
  {
    id: 10,
    type: 'large',
    title: 'Carlos Gutierrez',
    subtitle: 'Sports Event Manager',
    description: 'Planning nationwide marathons, basketball leagues, and athletic tournaments.',
    email: 'carlos.gutierrez@example.com',
    image: Reydel,
    gridConfig: {
      colSpan: 2,
      rowSpan: 16,
    },
    backgroundColor: 'bg-yellow-100',
    buttonText: 'Collab',
  },
];
