import Reydel from '@/assets/profiles/Reydel.jpg';
import Tech from '@/assets/xlab/tech.jpg';
import SJR from '@/assets/xlab/sjr.jpg';
import Lakbay from '@/assets/xlab/lakbay.jpg';
import Carlos from '@/assets/xlab/podcast.jpg';
import Kulto from '@/assets/xlab/kulto.jpg';
import Maria from '@/assets/xlab/tala.jpg';
import Anna from '@/assets/xlab/anna.jpg';
export const Collaborator = [
  {
    id: 1,
    type: 'large',
    title: 'Kulturang Pinoy',
    subtitle: 'Cultural Events Team',
    description: 'Showcasing Filipino traditions through events.',
    email: 'info@kulturangpinoy.com',
    image: Kulto,
    gridConfig: {
      colSpan: 4,
      rowSpan: 3,
    },
    backgroundColor: 'bg-green-100',
    buttonText: 'Collab',
  },
  {
    id: 2,
    type: 'medium',
    title: 'SJR Events',
    subtitle: 'Event Coordinator',
    description: 'Organizing seamless corporate and community events with a focus on engagement.',
    email: 'jed@gmail.com',
    image: SJR,
    gridConfig: {
      colSpan: 2,
      rowSpan: 2,
    },
    backgroundColor: 'bg-blue-100',
    buttonText: 'Collab',
  },

  {
    id: 3,
    type: 'medium',
    title: 'Maria Santos',
    subtitle: 'Concert Organizer',
    description: 'Bringing OPM artists to the stage.',
    email: 'maria.santos@example.com',
    image: Maria,
    gridConfig: {
      colSpan: 1,
      rowSpan: 1,
    },
    backgroundColor: 'bg-black',
    buttonText: 'Collab',
  },
  {
    id: 4,
    type: 'small',
    title: 'Team Lakbay',
    subtitle: 'Travel & Advent Club',
    description: 'Curating fun travel experiences.',
    email: 'contact@teamlakbay.ph',
    image: Lakbay,
    gridConfig: {
      colSpan: 1,
      rowSpan: 1,
    },
    backgroundColor: 'bg-red-100',
    buttonText: 'Collab',
  },
  // {
  //   id: 5,
  //   type: 'extrasmall',
  //   title: 'Gabriel Reyes',
  //   subtitle: 'Festival Director',
  //   description: 'Managing cultural festivals.',
  //   email: 'gabriel.reyes@example.com',
  //   image: Reydel,
  //   gridConfig: {
  //     colSpan: 1,
  //     rowSpan: 4,
  //   },
  //   backgroundColor: 'bg-purple-100',
  //   buttonText: 'Collab',
  // },
  // {
  //   id: 6,
  //   type: 'extrasmall',
  //   title: 'Barkada Esports',
  //   subtitle: 'Gaming Tournament Hosts',
  //   description: 'Hosting esports battles.',
  //   email: 'support@barkadaesports.gg',
  //   image: Reydel,
  //   gridConfig: {
  //     colSpan: 1,
  //     rowSpan: 4,
  //   },
  //   backgroundColor: 'bg-yellow-100',
  //   buttonText: 'Collab',
  // },
  // {
  //   id: 7,
  //   type: 'large',
  //   title: 'Luzviminda Productions',
  //   subtitle: 'Event Management Agency',
  //   description: 'Bringing grand event concepts to reality with world-class planning and execution.',
  //   email: 'hello@luzvimindaproductions.ph',
  //   image: Reydel,
  //   gridConfig: {
  //     colSpan: 4,
  //     rowSpan: 8,
  //   },
  //   backgroundColor: 'bg-yellow-100',
  //   buttonText: 'Collab',
  // },
  // {
  //   id: 8,
  //   type: 'large',
  //   title: 'Anna Mendoza',
  //   subtitle: 'Wedding Planner',
  //   description: 'Creating magical wedding experiences tailored to the couple’s vision and culture.',
  //   email: 'anna.mendoza@example.com',
  //   image: Reydel,
  //   gridConfig: {
  //     colSpan: 2,
  //     rowSpan: 12,
  //   },
  //   backgroundColor: 'bg-yellow-100',
  //   buttonText: 'Collab',
  // },
  // {
  //   id: 9,
  //   type: 'medium',
  //   title: 'TechTalk PH',
  //   subtitle: 'Tech Conference Organizers',
  //   description: 'Hosting conferences that bring together innovators, developers, and startups.',
  //   email: 'info@techtalkph.com',
  //   image: Reydel,
  //   gridConfig: {
  //     colSpan: 2,
  //     rowSpan: 5,
  //   },
  //   backgroundColor: 'bg-yellow-100',
  //   buttonText: 'Collab',
  // },
  {
    id: 10,
    type: 'large',
    title: 'Carlos Gutierrez',
    subtitle: 'Podcast Host',
    description: 'Sharing stories and ideas that inspire and educate the world.',
    email: 'carlos.gutierrez@example.com',
    image: Carlos,
    gridConfig: {
      colSpan: 2,
      rowSpan: 15,
    },
    backgroundColor: 'bg-yellow-100',
    buttonText: 'Collab',
  },

  {
    id: 11,
    type: 'large',
    title: 'TechTalk PH',
    subtitle: 'Tech Conference Organizers',
    description: 'Hosting conferences that bring together innovators, developers, and startups.',
    email: 'info@techtalkph.com',
    image: Tech,
    gridConfig: {
      colSpan: 2,
      rowSpan: 15,
    },
    backgroundColor: 'bg-yellow-100',
    buttonText: 'Collab',
  },
  {
    id: 12,
    type: 'large',
    title: 'Anna Mendoza',
    subtitle: 'Wedding Planner',
    description: 'Creating magical wedding experiences tailored to the couple’s vision and culture.',
    email: 'anna.mendoza@example.com',
    image: Anna,
    gridConfig: {
      colSpan: 2,
      rowSpan: 15,
    },
    backgroundColor: 'bg-yellow-100',
    buttonText: 'Collab',
  },
];
