-- CreateTable
CREATE TABLE `Points` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `eventId` VARCHAR(191) NOT NULL,
    `points` INTEGER NOT NULL DEFAULT 0,
    `category` ENUM('HEALTH_WELLBEING', 'SUSTAINABILITY_ENVIRONMENT', 'SOCIAL_CONNECTION_SUPPORT', 'EDUCATION_EMPOWERMENT', 'ECONOMIC_STABILITY', 'TRUST_TRANSPARENCY', 'COLLABORATION_ENGAGEMENT', 'CIVIC_ENGAGEMENT_RESPONSIBILITY', 'INCLUSIVITY_DIVERSITY') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Points` ADD CONSTRAINT `Points_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
